// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJUUvPCYwexs2Pxr6ScRIRmqxyAkBRK0',
    appId: '1:109067555861:web:0467e2083b054565396a1c',
    messagingSenderId: '109067555861',
    projectId: 'buyit-79823',
    authDomain: 'buyit-79823.firebaseapp.com',
    storageBucket: 'buyit-79823.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiJPQ05LmDHGbO_y3IFfLktdYTovu9iMQ',
    appId: '1:109067555861:android:e368bd48a98938a1396a1c',
    messagingSenderId: '109067555861',
    projectId: 'buyit-79823',
    storageBucket: 'buyit-79823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuoYqVm0ILfac0ktSJuVCxLwZVpuHfwu0',
    appId: '1:109067555861:ios:9ed552703d857d9c396a1c',
    messagingSenderId: '109067555861',
    projectId: 'buyit-79823',
    storageBucket: 'buyit-79823.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );
}
